name: Pull Request CI

on:
  pull_request:

jobs:
  build-test-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Run tests
        run: cargo test --all --locked

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build package
        run: cargo build --all --locked --release