name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test --release
        
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: oxypack
          path: target/release/oxypack

